apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
  app: apiserver
spec:
  selector:
    app: apiserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP