apiVersion: v1
kind: Service
metadata:
  labels:
    app: sba-frontend
  name: sba-frontend
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sba-frontend
    release: v1
  type: ClusterIP
