apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dynamodb
  name: dynamodb
spec:
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        image: hub.brainupgrade.net/harish/dynamodb:usage
        imagePullPolicy: IfNotPresent
        name: dynamodb
   
